[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

build_flags = 
  -Os

board_build.partitions = partitions.csv
board_build.filesystem = littlefs
board_build.flash_mode = dio
board_build.flash_size = 4MB

lib_deps =
  bblanchon/ArduinoJson@^6.21.3
  https://github.com/esphome/ESPAsyncWebServer.git
  https://github.com/esphome/AsyncTCP.git
  marcoschwartz/LiquidCrystal_I2C@^1.1.4
  adafruit/DHT sensor library@^1.4.6
  adafruit/Adafruit Unified Sensor@^1.1.14
  paulstoffregen/OneWire@^2.3.8
  milesburton/DallasTemperature@^3.11.0

lib_ldf_mode = deep+
