[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_speed  = 921600

board_build.partitions = partitions.csv
board_build.filesystem = littlefs
board_build.flash_mode = dio
board_build.flash_size = 16MB

build_flags =
  -Os
  -D ARDUINO_USB_CDC_ON_BOOT=1
  -D ARDUINO_USB_MODE=1

lib_deps =
  bblanchon/ArduinoJson@^6.21.3
  4-20ma/ModbusMaster@^2.0.1
  https://github.com/esphome/ESPAsyncWebServer.git
  https://github.com/esphome/AsyncTCP.git

lib_ldf_mode = deep+
